spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eazybank?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true


# Spring Security FilterChainProxy 디버깅 활성화
logging:
  level:
    'org.springframework.security.web.FilterChainProxy': TRACE