spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create # application 실행 시 기존 테이블 drop 후 create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug # 발생되는 쿼리문을 로그로 출력

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET}
    region:
        static: ${AWS_REGION}
    stack:
      auto: false
