spring:
  datasource:
    url: jdbc:mysql://localhost:3308/test?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: hope
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # application 실행 시 기존 테이블 drop 후 create
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6381

cloud:
  aws:
    credentials:
      access-key: "test"
      secret-key: "test"
    s3:
      bucket: "test"
    region:
      static: "test"
    stack:
      auto: false