spring:
  datasource:
    url: jdbc:mysql://localhost:3308/test?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: hope
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver


cloud:
  aws:
    credentials:
      access-key: "test"
      secret-key: "test"
    s3:
      bucket: "test"
    region:
      static: "test"
    stack:
      auto: false