spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: update # application 실행 시 기존 테이블 drop 후 create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug # 발생되는 쿼리문을 로그로 출력