spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qr_code?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create # application 실행 시 기존 테이블 drop 후 create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug # 발생되는 쿼리문을 로그로 출력