version: '3.7'

services:
  db:
    image: mysql:8.0
    restart: always
    container_name: mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: hope
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3308:3306"
    volumes:
      - mysql:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --port 6379
    hostname: hope
    ports:
      - "6381:6379"
    restart: always

volumes:
  mysql: