version: '3.7'

services:
  db:
    image: mysql:8.0
    restart: always
    container_name: mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: hope
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - mysql:/var/lib/mysql


volumes:
  mysql: