name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      working-directory: ./spring-devops

    - name: Build with Gradle Wrapper
      run: ./gradlew build
      working-directory: ./spring-devops
      env:
        AWS_RDS: ${{ secrets.AWS_RDS }}
        AWS_RDS_USERNAME: ${{ secrets.AWS_RDS_USERNAME }}
        AWS_RDS_PASSWORD: ${{ secrets.AWS_RDS_PASSWORD }}
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        
